### ISSUE TITLE
Tests failure due to 'authorization issue'

### ISSUE THREAD

**Issue by MahimaGaikwad** [ibm-watson-iot/iot-python#206]
We are trying to install package "iot-python" from source(https://github.com/ibm-watson-iot/iot-python) on PPC64LE. We are able to successfully install the package, However when executing tests via "tox" command we see some failures.

Steps Performed for install and testing:
$ git clone https://github.com/ibm-watson-iot/iot-python
$ cd iot-python
$ pip install tox
$ export WIOTP_API_KEY=a-ef7dba-yoiqn7qwam
$ export WIOTP_API_TOKEN=ZeYmFKFmJFH*tk1F2N
$ tox

Expected Result: 
	270 test should pass

Actual Result: 
	245 test pass, 23 failed, 1 error

Error message:
	wiotp.sdk.exceptions.ConnectionException: Not authorized: s (d:ef7dba:iotpython_test_device:00189c35-cdb8-4e09-a8c5-e567d6307d96, use-token-auth, 25a62128-ae65-42f2-bd40-fab9e6b894b6)

Logs:
---------------------------- Captured stderr call -----------------------------
2021-04-14 06:27:50,681   wiotp.sdk.device.client.DeviceClient  WARNING Unable to encrypt messages because client configuration has overridden port selection to an insecure port (1883)
2021-04-14 06:27:51,190   wiotp.sdk.device.client.DeviceClient  CRITICAL Not authorized: s (d:ef7dba:iotpython_test_device:00189c35-cdb8-4e09-a8c5-e567d6307d96, use-token-auth, 25a62128-ae65-42f2-bd40-fab9e6b894b6)
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 2942, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 3030, in _handle_connack
    self, self._userdata, flags_dict, result)
  File "/iot-python/src/wiotp/sdk/client.py", line 342, in _onConnect
    ConnectionException("Not authorized: s (%s, %s, %s)" % (self.clientId, self.username, self.password))
  File "/iot-python/src/wiotp/sdk/client.py", line 236, in _logAndRaiseException
    raise e
wiotp.sdk.exceptions.ConnectionException: Not authorized: s (d:ef7dba:iotpython_test_device:00189c35-cdb8-4e09-a8c5-e567d6307d96, use-token-auth, 25a62128-ae65-42f2-bd40-fab9e6b894b6)

2021-04-14 06:28:51,031   wiotp.sdk.device.client.DeviceClient  CRITICAL Operation timed out connecting to IBM Watson IoT Platform: ef7dba.messaging.internetofthings.ibmcloud.com

**Comment by durera** [comment]
```
2021-04-14 06:27:50,681 wiotp.sdk.device.client.DeviceClient WARNING Unable to encrypt messages because client configuration has overridden port selection to an insecure port (1883)
```

Have you enabled insecure connections in your organization settings?  By default this is disabled for security reasons and must be explictly enabled.

For additional support in debugging connection issues please raise a ticket using IBM Support portal :+1:
