### ISSUE TITLE
Update of device meta data from Watson IOT dashboard produces error on device

### ISSUE THREAD

**Issue by hirschbrat** [ibm-watson-iot/iot-python#67]
Using Watson IOT dashboard to change device metadata produces the following error on the device:

> 2017-05-07 11:14:50,828   ibmiotf.device.ManagedClient  INFO    Message received on topic :iotdm-1/device/update with payload {"d":{"fields":[{"field":"metadata","value":{"metadata":"value"}}]}}
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2630, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1410, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 926, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1209, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1802, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2278, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2468, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2618, in _handle_on_message
    t[1](self, self._userdata, message)
  File "/usr/local/lib/python2.7/dist-packages/ibmiotf/device.py", line 833, in __onUpdatedDevice
    reqId = data['reqId']
KeyError: 'reqId'

**Comment by amprasanna** [comment]
This issue is fixed in https://github.com/ibm-watson-iot/iot-python/pull/72
