### ISSUE TITLE
TypeError run-time crash after publishing in a loop for a long time

### ISSUE THREAD

**Issue by mravkine** [ibm-watson-iot/iot-python#99]
Hello,

After 64k published messages (with qos=0 and no publish call-back defined) the following error occurs and the client ceases to function:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mike/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 2650, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/mike/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 1481, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/mike/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 1019, in loop
    rc = self.loop_write(max_packets)
  File "/home/mike/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 1309, in loop_write
    rc = self._packet_write()
  File "/home/mike/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 1895, in _packet_write
    self.on_publish(self, self._userdata, packet['mid'])
  File "/home/mike/.local/lib/python3.5/site-packages/ibmiotf/__init__.py", line 189, in on_publish
    midOnPublish()
TypeError: 'NoneType' object is not callable
```

This is the function responsible:

```
    def on_publish(self, mosq, obj, mid):
        with self._messagesLock:
            self.messages = self.messages + 1
            if mid in self._onPublishCallbacks:
                midOnPublish = self._onPublishCallbacks.get(mid)
                del self._onPublishCallbacks[mid]
                midOnPublish()
            else:
                # record the fact that paho callback has already come through so it can be called inline
                # with the publish.
                self._onPublishCallbacks[mid] = None
```

I believe the problem here is that "mid" is a 16-bit unsigned quantity according to protocol specs, so it will wrap around after 64k "None"s have been uselessly shoved into the _onPublishCallbacks array and eventually the true branch of the condition will be taken and crash when attempting to invoke one of those "None"s..

My work-around is to simply remove the "else" branch of the condition, I see that this is trying to avoid a race condition with the publish thread, but it needs to better handle the case where no call back is defined and not grow this array to 64k entries..

**Comment by icraggs** [comment]
Hello.  Thanks for raising the issue.  I've created a proposed fix in the develop branch, which I think caters for all the eventualities.

**Comment by mravkine** [comment]
Perfect, thanks for looking into this!

**Comment by icraggs** [comment]
Out of interest, did you have chance to try the changes out?
